export default () => {
  return [
    {
      title: '', // Invalid title
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '', // Invalid description
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      // No title
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      // No description
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      // No img list
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: [], // Invalid img list
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: 'invalid start date', // Invalid start date
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      // No start date
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: 'invalid end date', // Invalid end date
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: 123, // Invalid open time
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      // No open time
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 'invalid genre idx', // Invalid genre idx
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      // No genre
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: 'Invalid style idx list', // Invalid styleIdxList
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: new Date(), // Invalid styleIdxList
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      // No styleIdxList
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 'Invalid age idx', // Invalid ageIdx
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      // No ageIdx
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: 123, // Invalid location
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: 'invalid location', // Invalid location
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 123123, // Invalid detailAddress
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        // No detailAddress
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: 123123, // Invalid region1Depth
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        // No region2Depth
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: 123123123, // Invalid region2Depth
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        // No region2Depth
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: '0', // Invalid positionX
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        // No positionX
        //positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 'invalid', // Invalid positionY
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        // No hCode
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: 0, // Invalid bCode
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        // No bCode
        //bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: 123, // Invalid isFee
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      // No isFee
      //isFee: true,
      isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: 1234, // Invalid isReservation
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      // No isReservation
      //isReservation: true,
      isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: 123, // Invalid isParking
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      // No isParking
      //isParking: true,
      isPet: true,
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      isPet: 123, // Invalid isPet
    },
    {
      title: '도라에몽',
      description: '도라에몽 팝업 스토어 입니다.',
      websiteLink: 'liket.site',
      imgList: ['/content/test.img'],
      startDate: new Date(),
      endDate: new Date(),
      openTime: '평일 6 ~ 12시',
      genreIdx: 1,
      styleIdxList: [1, 2, 3],
      ageIdx: 1,
      location: {
        detailAddress: 'LH아파트 1250호',
        address: '전북 익산시 부송동 100',
        region1Depth: '서울',
        region2Depth: '강동구',
        positionX: 126.99597295767953,
        positionY: 35.97664845766847,
        hCode: '4514069000',
        bCode: '4514013400',
      },
      isFee: true,
      isReservation: true,
      isParking: true,
      // No isPet
      //isPet: true,
    },
  ];
};
