services:
  postgresql:
    image: postgres:15.4
    restart: always
    container_name: liket-admin-test-DB
    ports:
      - '5501:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ../../rdb/:/rdb/
