name: "[Admin-Server] Dev Deploy"   

on:
  push:
    branches:
      - develop
    paths:
      - apps/admin-server/**
      - prisma/schema.prisma
      - libs/**
      - .github/workflows/admin-server.dev.deploy.yml
      - '!apps/admin-server/test/**'
      - '!apps/admin-server/README.md'
      - '!apps/admin-server/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.COMMON_DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.COMMON_DOCKER_HUB_USER }}" --password-stdin

      - name: Build and push image to docker hub
        env:
          IMAGE_TAG: latest
        run: |
          docker build -f apps/admin-server/Dockerfile -t ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-backoffice-dev-api-server .
          docker push ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-backoffice-dev-api-server:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass 
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to dev server
        env:
          HOST: ${{ secrets.COMMON_HOME_SERVER_HOST }}
          PW: ${{ secrets.COMMON_HOME_SERVER_PW }}
          USER: ${{ secrets.COMMON_HOME_SERVER_USER }}
        run: |
          sshpass -p "$PW" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            docker pull ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-backoffice-dev-api-server:latest
            docker stop ${{ secrets.ADMIN_SERVER_DEV_DEPLOY_CONTAINER_NAME }} || true
            docker rm ${{ secrets.ADMIN_SERVER_DEV_DEPLOY_CONTAINER_NAME }} || true
            
            docker run -d -p 3001:3000 \
              --name ${{ secrets.ADMIN_SERVER_DEV_DEPLOY_CONTAINER_NAME }} \
              --env-file ${{ secrets.ADMIN_SERVER_DEV_DEPLOY_ENV_PATH }} \
              -v /home/jochong/chipmunkers/instagram-session/ig-session.json:/usr/src/app/ig-session.json \
              ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-backoffice-dev-api-server:latest
          EOF
