name: "[Batch Server] Dev Deploy"   

on:
  push:
    branches:
      - develop
    paths:
      - apps/batch-server/**
      - libs/**
      - .github/workflows/batch-server.dev.deploy.yml
      - '!apps/batch-server/test/**'
      - '!apps/batch-server/README.md'
      - '!apps/batch-server/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.COMMON_DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.COMMON_DOCKER_HUB_USER }}" --password-stdin

      - name: Build and push image to docker hub
        env:
          IMAGE_TAG: latest
        run: |
          docker build -f apps/batch-server/Dockerfile -t ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-batch-server .
          docker push ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-batch-server:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass 
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to dev server
        env:
          HOST: ${{ secrets.COMMON_HOME_SERVER_HOST }}
          PW: ${{ secrets.COMMON_HOME_SERVER_PW }}
          USER: ${{ secrets.COMMON_HOME_SERVER_USER }}
        run: |
          sshpass -p "$PW" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            docker pull ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-batch-server:latest
            docker stop ${{ secrets.BATCH_SERVER_DEV_DEPLOY_CONTAINER_NAME }} || true
            docker rm ${{ secrets.BATCH_SERVER_DEV_DEPLOY_CONTAINER_NAME }} || true
            
            docker run -d -p 3003:3000 --name ${{ secrets.BATCH_SERVER_DEV_DEPLOY_CONTAINER_NAME }} --env-file ${{ secrets.BATCH_SERVER_DEV_DEPLOY_ENV_PATH }} ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-batch-server:latest
          EOF
