name: Build and Deploy Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and push image to docker hub
        env:
          IMAGE_TAG: latest
        run: |
          docker build -f ./dev-deploy/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-api-server .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-api-server:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass 
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to dev server
        env:
          HOST: ${{ secrets.DEV_SERVER_HOST }}
          PW: ${{ secrets.DEV_SERVER_PW }}
          USER: ${{ secrets.DEV_SERVER_USER }}
        run: |
          sshpass -p "$PW" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-api-server:latest
            docker stop ${{ secrets.DEV_SERVER_CONTAINER_NAME }} || true
            docker rm ${{ secrets.DEV_SERVER_CONTAINER_NAME }} || true
            
            docker run -d -p 3000:3000 --name ${{ secrets.DEV_SERVER_CONTAINER_NAME }} --env-file ${{ secrets.DEV_ENV_FILE_PATH }} ${{ secrets.DOCKER_HUB_USERNAME }}/liket-mobile-dev-api-server:latest
          EOF
