name: "[User-Server] Dev Deploy"

on:
  push:
    branches:
      - develop
    paths:
      - apps/user-server/**
      - libs/**
      - .github/user-server.dev.deploy.yml
    paths-ignore:
      - apps/user-server/test/**
      - apps/user-server/README.md
      - scripts/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.COMMON_DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.COMMON_DOCKER_HUB_USER }}" --password-stdin

      - name: Build and push image to docker hub
        env:
          IMAGE_TAG: latest
        run: |
          docker build -f apps/user-server/Dockerfile -t ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-mobile-dev-api-server .
          docker push ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-mobile-dev-api-server:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass 
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy dev API server to home-server
        env:
          HOST: ${{ secrets.COMMON_HOME_SERVER_HOST }}
          PW: ${{ secrets.COMMON_HOME_SERVER_PW }}
          USER: ${{ secrets.COMMON_HOME_SERVER_USER }}
        run: |
          sshpass -p "$PW" ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            docker pull ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-mobile-dev-api-server:latest
            docker stop ${{ secrets.USER_SERVER_DEV_DEPLOY_CONATINER_NAME }} || true
            docker rm ${{ secrets.USER_SERVER_DEV_DEPLOY_CONATINER_NAME }} || true
            
            docker run -d -p 3000:3000 --name ${{ secrets.USER_SERVER_DEV_DEPLOY_CONATINER_NAME }} --env-file ${{ secrets.USER_SERVER_DEV_DEPLOY_ENV_PATH }} ${{ secrets.COMMON_DOCKER_HUB_USER }}/liket-mobile-dev-api-server:latest
          EOF
